DROP TABLE IF EXISTS POSITION;

CREATE TABLE POSITION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL
);

DROP TABLE IF EXISTS CANDIDATE;

CREATE TABLE CANDIDATE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    LAST_NAME VARCHAR(150) NOT NULL,
    ADDRESS VARCHAR(250) NOT NULL,
    CELLPHONE VARCHAR(15) NOT NULL,
    CITY_NAME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERSON BIGINT NOT NULL,
    POSITION BIGINT NOT NULL,
    SALARY INT NOT NULL,
    FOREIGN KEY (PERSON) REFERENCES CANDIDATE(ID),
    FOREIGN KEY (POSITION) REFERENCES POSITION(ID)
);

INSERT INTO POSITION (NAME) VALUES ('dev');
INSERT INTO POSITION (NAME) VALUES ('qa');

INSERT INTO Candidate (NAME, LAST_NAME, ADDRESS, CELLPHONE, CITY_NAME) VALUES ('Camilo', 'ruiz', 'cra', '124', 'Medellin');
INSERT INTO Candidate (NAME, LAST_NAME, ADDRESS, CELLPHONE, CITY_NAME) VALUES ('Andress', 'escobar', 'cra', '1244', 'Envigado');
INSERT INTO Candidate (NAME, LAST_NAME, ADDRESS, CELLPHONE, CITY_NAME) VALUES ('luis', 'perez', 'cra', '124', 'Medellin');
INSERT INTO Candidate (NAME, LAST_NAME, ADDRESS, CELLPHONE, CITY_NAME) VALUES ('pedro', 'castro', 'cra', '1244', 'Envigado');

INSERT INTO Employee (PERSON, POSITION, SALARY) VALUES (1, 1, 2000);
INSERT INTO Employee (PERSON, POSITION, SALARY) VALUES (2, 1, 1000);
INSERT INTO Employee (PERSON, POSITION, SALARY) VALUES (3, 2, 1500);
INSERT INTO Employee (PERSON, POSITION, SALARY) VALUES (4, 2, 1000);